/* Generated By:JavaCC: Do not edit this line. AnalisadorLexicoConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int DEFINE = 8;
  /** RegularExpression Id. */
  int START = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int SET = 11;
  /** RegularExpression Id. */
  int READ = 12;
  /** RegularExpression Id. */
  int SHOW = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int LOOP = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int NUM = 19;
  /** RegularExpression Id. */
  int REAL = 20;
  /** RegularExpression Id. */
  int TEXT = 21;
  /** RegularExpression Id. */
  int FLAG = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int ERRO_ID_INICIA_COM_DIGITO = 25;
  /** RegularExpression Id. */
  int ERRO_ID_DIGITOS_CONSECUTIVOS = 26;
  /** RegularExpression Id. */
  int ERRO_ID_TERMINA_COM_DIGITO = 27;
  /** RegularExpression Id. */
  int IDENTIFIER = 28;
  /** RegularExpression Id. */
  int LETRA = 29;
  /** RegularExpression Id. */
  int DIGITO = 30;
  /** RegularExpression Id. */
  int ERRO_REAL_FRACAO_LONGA = 31;
  /** RegularExpression Id. */
  int ERRO_REAL_INTEIRO_LONGO = 32;
  /** RegularExpression Id. */
  int ERRO_REAL_INCOMPLETO = 33;
  /** RegularExpression Id. */
  int ERRO_INT_LONGO = 34;
  /** RegularExpression Id. */
  int CONST_REAL = 35;
  /** RegularExpression Id. */
  int CONST_INT = 36;
  /** RegularExpression Id. */
  int CONST_LITERAL = 37;
  /** RegularExpression Id. */
  int ERRO_LITERAL = 38;
  /** RegularExpression Id. */
  int OP_REL_LTLT_EQ = 39;
  /** RegularExpression Id. */
  int OP_REL_GTGT_EQ = 40;
  /** RegularExpression Id. */
  int OP_REL_EQ = 41;
  /** RegularExpression Id. */
  int OP_REL_NEQ = 42;
  /** RegularExpression Id. */
  int OP_REL_LTLT = 43;
  /** RegularExpression Id. */
  int OP_REL_GTGT = 44;
  /** RegularExpression Id. */
  int OP_ARIT_POW = 45;
  /** RegularExpression Id. */
  int OP_ARIT_DIVINT = 46;
  /** RegularExpression Id. */
  int OP_ARIT_SUM = 47;
  /** RegularExpression Id. */
  int OP_ARIT_SUB = 48;
  /** RegularExpression Id. */
  int OP_ARIT_MUL = 49;
  /** RegularExpression Id. */
  int OP_ARIT_DIV = 50;
  /** RegularExpression Id. */
  int OP_ARIT_MOD = 51;
  /** RegularExpression Id. */
  int OP_LOGIC_AND = 52;
  /** RegularExpression Id. */
  int OP_LOGIC_OR = 53;
  /** RegularExpression Id. */
  int OP_LOGIC_NOT = 54;
  /** RegularExpression Id. */
  int ASSIGN = 55;
  /** RegularExpression Id. */
  int SEMICOLON = 56;
  /** RegularExpression Id. */
  int COMMA = 57;
  /** RegularExpression Id. */
  int LPAREN = 58;
  /** RegularExpression Id. */
  int RPAREN = 59;
  /** RegularExpression Id. */
  int LBRACKET = 60;
  /** RegularExpression Id. */
  int RBRACKET = 61;
  /** RegularExpression Id. */
  int LBRACE = 62;
  /** RegularExpression Id. */
  int RBRACE = 63;
  /** RegularExpression Id. */
  int COLON = 64;
  /** RegularExpression Id. */
  int DOT = 65;
  /** RegularExpression Id. */
  int ERRO_LEXICO = 66;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENT>",
    "\"begin\"",
    "\"define\"",
    "\"start\"",
    "\"end\"",
    "\"set\"",
    "\"read\"",
    "\"show\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"loop\"",
    "\"while\"",
    "\"num\"",
    "\"real\"",
    "\"text\"",
    "\"flag\"",
    "\"true\"",
    "\"false\"",
    "<ERRO_ID_INICIA_COM_DIGITO>",
    "<ERRO_ID_DIGITOS_CONSECUTIVOS>",
    "<ERRO_ID_TERMINA_COM_DIGITO>",
    "<IDENTIFIER>",
    "<LETRA>",
    "<DIGITO>",
    "<ERRO_REAL_FRACAO_LONGA>",
    "<ERRO_REAL_INTEIRO_LONGO>",
    "<ERRO_REAL_INCOMPLETO>",
    "<ERRO_INT_LONGO>",
    "<CONST_REAL>",
    "<CONST_INT>",
    "<CONST_LITERAL>",
    "<ERRO_LITERAL>",
    "\"<<=\"",
    "\">>=\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"**\"",
    "\"%%\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\".\"",
    "<ERRO_LEXICO>",
  };

}
